import tkinter
from tkinter import *
top=Tk()
top.title("Alert !")
Roll=Label(top,text='Roll no')
Roll.grid(row=0,column=0)
e1=Entry(top)
e1.grid(row=0,column=1)
Name=Label(top,text='Name')
Name.grid(row=1,column=0)
e2=Entry(top)
e2.grid(row=1,column=1)
Course=Label(top,text='Roll no')
Course.grid(row=2,column=0)
e3=Entry(top)
e3.grid(row=2,column=1)
top.geometry('400x250')
Submit=Button(top,text='Submit',fg='Blue')
Submit.grid(row=8,column=4)
top.mainloop()
